# Generated by Django 5.2.3 on 2025-06-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(choices=[('N', 'Norte'), ('S', 'Sur'), ('E', 'Este'), ('O', 'Oeste')], max_length=1)),
                ('tipo', models.CharField(choices=[('urbana', 'Urbana'), ('rural', 'Rural')], max_length=6)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_viviendas', models.PositiveIntegerField()),
                ('numero_parques', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('numero_edificios_residenciales', models.PositiveIntegerField()),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrios', to='ordenamiento.parroquia')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
